"""Co-authored-by trailers for commits made inside a session dir (#518).

c-lord clones a repo per thread and hands the checkout to Claude, so every
commit Claude makes carries only the *host's* git identity. Nothing in the
history records **which Discord user asked for the change** — with several
people in one server their work all collapses into a single author.

This module closes that gap by installing a ``prepare-commit-msg`` hook into
the session dir. A hook (rather than a system-prompt instruction) is used
deliberately: an instruction relies on Claude remembering, which is the exact
failure mode #491 documents. The hook runs for ``git commit -m`` and survives
``--no-verify`` (that flag skips *pre-commit* and *commit-msg*, not
*prepare-commit-msg*).

The Discord display name never reaches the hook *script*. c-lord writes the
rendered trailers to a data file and the hook reads them line by line, so a
name like ``a$(rm -rf /)b`` is data, never shell.
"""

from __future__ import annotations

import logging
import os
import re
import shlex
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

HOOK_NAME = "prepare-commit-msg"
HOOK_MARKER = "# c-lord:coauthor-hook"
DATA_FILE_NAME = "clord-coauthors"

#: Claude's own trailer. Added as a safety net only — when Claude already
#: signed the message (its own trailer names the model, e.g. "Claude Opus 5"),
#: the hook keeps Claude's version and does not add this one on top.
CLAUDE_COAUTHOR = "Co-Authored-By: Claude <noreply@anthropic.com>"

DISCORD_EMAIL_DOMAIN = "users.noreply.discord.com"

_ENV_FLAG = "CLORD_COAUTHOR"
_OFF_VALUES = {"0", "false", "no", "off"}
_MAX_NAME_LEN = 64
_CONTROL_CHARS = re.compile(r"[\x00-\x1f\x7f]")

# The hook body is static; only DATA (a c-lord-controlled path) is templated.
# Every failure path exits 0 — a broken hook must never block Claude's commit.
_HOOK_TEMPLATE = """\
#!/bin/sh
{marker}
# Auto-generated by c-lord (see c_lord/coauthor.py, issue #518).
# Rewritten at the start of every turn — local edits will be lost.
#
# Appends the Co-authored-by trailers listed in DATA to the commit message.
# Trailers already present (matched by e-mail address) are left alone, so
# amending or re-committing never duplicates them.
DATA={data_path}
MSG="$1"
SOURCE="$2"

[ -n "$MSG" ] || exit 0
[ -f "$DATA" ] || exit 0
[ -f "$MSG" ] || exit 0
case "$SOURCE" in
  merge|squash) exit 0 ;;
esac
command -v git >/dev/null 2>&1 || exit 0

set --
while IFS= read -r line || [ -n "$line" ]; do
  case "$line" in
    ''|'#'*) continue ;;
  esac
  email=${{line#*<}}
  email=${{email%%>*}}
  if [ -n "$email" ] && grep -qiF "<$email>" "$MSG"; then
    continue
  fi
  set -- "$@" --trailer "$line"
done < "$DATA"

[ "$#" -gt 0 ] || exit 0
git interpret-trailers --in-place --if-exists addIfDifferent "$@" "$MSG" || exit 0
exit 0
"""


def coauthor_enabled() -> bool:
    """Whether trailer injection is on. Defaults to on (Zero-Config)."""
    return os.getenv(_ENV_FLAG, "").strip().lower() not in _OFF_VALUES


def _sanitize_name(raw: str) -> str:
    """Reduce a Discord display name to something safe on a trailer line.

    Newlines are what matter most: without stripping them a display name
    could forge additional trailers. ``<``/``>`` would break the address.
    """
    # Cut at the first control character rather than replacing it: a display
    # name is one line by definition, and anything past a newline is an
    # attempt to append a line (i.e. forge a second trailer), not a name.
    name = _CONTROL_CHARS.split(raw or "", maxsplit=1)[0]
    name = name.replace("<", "").replace(">", "")
    name = " ".join(name.split())
    if len(name) > _MAX_NAME_LEN:
        name = name[:_MAX_NAME_LEN].rstrip()
    return name


def discord_trailer(user: Any | None) -> str | None:
    """Render the ``Co-authored-by`` trailer for a Discord user.

    Args:
        user: A ``discord.Member`` / ``discord.User`` (anything exposing
            ``id`` and ``display_name``/``name``), or None when the run has
            no human behind it (scheduler, etc.).

    Returns:
        The trailer line, or None when no usable identity is available.
    """
    if user is None:
        return None
    user_id = getattr(user, "id", None)
    if not isinstance(user_id, int) or isinstance(user_id, bool) or user_id <= 0:
        return None

    raw = getattr(user, "display_name", None) or getattr(user, "name", None) or ""
    name = _sanitize_name(str(raw)) or f"discord-{user_id}"
    return f"Co-authored-by: {name} <{user_id}@{DISCORD_EMAIL_DOMAIN}>"


def build_trailers(user: Any | None) -> list[str]:
    """Return the trailer lines for a turn, most specific first."""
    trailers = []
    discord = discord_trailer(user)
    if discord is not None:
        trailers.append(discord)
    trailers.append(CLAUDE_COAUTHOR)
    return trailers


def _git_path(repo_dir: str | os.PathLike[str], what: str) -> Path | None:
    """Resolve ``git rev-parse --git-path <what>`` inside ``repo_dir``."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--git-path", what],
            cwd=str(repo_dir),
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        logger.warning("coauthor: git rev-parse failed in %s: %s", repo_dir, exc)
        return None
    if result.returncode != 0:
        return None
    raw = result.stdout.strip()
    if not raw:
        return None
    path = Path(raw)
    return path if path.is_absolute() else Path(repo_dir) / path


def _is_inside(path: Path, parent: Path) -> bool:
    """Whether ``path`` resolves to somewhere under ``parent``."""
    try:
        resolved = path.resolve()
        root = parent.resolve()
    except OSError:
        return False
    return resolved == root or root in resolved.parents


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _remove(path: Path) -> None:
    try:
        path.unlink()
    except FileNotFoundError:
        pass
    except OSError as exc:
        logger.warning("coauthor: could not remove %s: %s", path, exc)


def install_coauthor_hook(
    repo_dir: str | os.PathLike[str],
    user: Any | None = None,
) -> str | None:
    """Install (or refresh) the ``prepare-commit-msg`` hook in ``repo_dir``.

    Idempotent, and called once per turn so the trailer always names the user
    who triggered *this* turn.

    Args:
        repo_dir: The session dir (a git checkout).
        user: The Discord user who triggered the turn, or None.

    Returns:
        Absolute path to the installed hook, or None when nothing was
        installed (not a git repo, disabled, or a foreign hook is in the way).
    """
    git_dir = _git_path(repo_dir, ".")
    hooks_dir = _git_path(repo_dir, "hooks")
    if git_dir is None or hooks_dir is None:
        logger.debug("coauthor: %s is not a git repo, skipping hook", repo_dir)
        return None

    # Containment: only ever write inside *this* session's git dir. A global
    # `core.hooksPath` would otherwise make a per-session hook leak into every
    # repo on the host, and a husky-style in-tree `.husky/` would leave an
    # untracked file in the user's checkout for `git add -A` to sweep up.
    if not _is_inside(hooks_dir, git_dir):
        logger.warning(
            "coauthor: core.hooksPath points outside %s's git dir (%s) — refusing to "
            "write there; Co-authored-by trailers are off for this session",
            repo_dir,
            hooks_dir,
        )
        return None

    data_path = git_dir / DATA_FILE_NAME
    hook_path = hooks_dir / HOOK_NAME

    if not coauthor_enabled():
        # Scrub our own hook so a stale one can't keep signing commits after
        # the operator turned the feature off. Foreign hooks are left alone.
        if hook_path.is_file() and HOOK_MARKER in _read(hook_path):
            _remove(hook_path)
        _remove(data_path)
        return None

    if hook_path.exists() and HOOK_MARKER not in _read(hook_path):
        logger.warning(
            "coauthor: %s already has a non-c-lord %s hook — not overwriting it; "
            "Co-authored-by trailers will not be added for this session",
            repo_dir,
            HOOK_NAME,
        )
        return None

    try:
        data_path.write_text("\n".join(build_trailers(user)) + "\n", encoding="utf-8")
        hooks_dir.mkdir(parents=True, exist_ok=True)
        hook_path.write_text(
            _HOOK_TEMPLATE.format(marker=HOOK_MARKER, data_path=shlex.quote(str(data_path))),
            encoding="utf-8",
        )
        hook_path.chmod(0o755)
    except OSError as exc:
        logger.warning("coauthor: failed to install hook in %s: %s", repo_dir, exc)
        return None

    logger.debug("coauthor: hook installed at %s", hook_path)
    return str(hook_path)
