"""ccdb CLI — interactive setup wizard and bot launcher.

Usage:
    ccdb setup   — interactive wizard: creates .env from prompts
    ccdb start   — start the bot (reads .env)
    ccdb         — show help

Install via:
    uvx --from git+https://github.com/ebibibi/claude-code-discord-bridge ccdb setup
"""

from __future__ import annotations

import argparse
import asyncio
import os
import subprocess
import sys
from pathlib import Path

# aiohttp is an optional dependency ([api] extra) but is already present in the
# dev environment and widely installed.  We import lazily so that the core
# package still works without it — the setup wizard will surface a clear error.


# ---------------------------------------------------------------------------
# Public helpers (tested directly)
# ---------------------------------------------------------------------------


async def validate_token(token: str) -> str | None:
    """Call GET /users/@me with the given bot token.

    Returns "username#discriminator" on success, None on failure.
    """
    try:
        import aiohttp
    except ImportError:
        _die("aiohttp is required for token validation.  Install with: pip install aiohttp")

    headers = {"Authorization": f"Bot {token}" if not token.startswith("Bot ") else token}
    url = "https://discord.com/api/v10/users/@me"
    try:
        async with aiohttp.ClientSession() as session, session.get(url, headers=headers) as resp:
            if resp.status != 200:
                return None
            data = await resp.json()
            name = data.get("username", "Unknown")
            disc = data.get("discriminator", "0")
            return f"{name}#{disc}"
    except Exception:
        return None


async def fetch_channels(token: str) -> list[tuple[str, str, str]]:
    """Return a list of (channel_id, channel_name, guild_name) for all text channels.

    Returns [] if the token is invalid or the bot isn't in any guild.
    """
    try:
        import aiohttp
    except ImportError:
        return []

    headers = {"Authorization": f"Bot {token}" if not token.startswith("Bot ") else token}
    base = "https://discord.com/api/v10"
    result: list[tuple[str, str, str]] = []
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(f"{base}/users/@me/guilds", headers=headers) as resp:
                if resp.status != 200:
                    return []
                guilds = await resp.json()

            for guild in guilds:
                guild_id = guild["id"]
                guild_name = guild["name"]
                async with session.get(
                    f"{base}/guilds/{guild_id}/channels", headers=headers
                ) as resp2:
                    if resp2.status != 200:
                        continue
                    channels = await resp2.json()
                    for ch in channels:
                        if ch.get("type") == 0:  # GUILD_TEXT
                            result.append((ch["id"], ch["name"], guild_name))
    except Exception:
        return []
    return result


def write_env(
    *,
    path: Path,
    token: str,
    channel_id: str,
    owner_id: str,
    working_dir: str,
    model: str,
    overwrite: bool = False,
) -> None:
    """Write a .env file with the given configuration.

    Raises FileExistsError if the file already exists and overwrite=False.
    """
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists")

    lines = [
        "# Generated by `ccdb setup`",
        f"DISCORD_BOT_TOKEN={token}",
        f"DISCORD_CHANNEL_ID={channel_id}",
        f"DISCORD_OWNER_ID={owner_id}",
        "",
        "CLAUDE_COMMAND=claude",
        f"CLAUDE_MODEL={model}",
        "CLAUDE_PERMISSION_MODE=acceptEdits",
        f"CLAUDE_WORKING_DIR={working_dir}",
        "",
        "MAX_CONCURRENT_SESSIONS=3",
        "SESSION_TIMEOUT_SECONDS=300",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def check_claude_cli() -> bool:
    """Return True if the Claude Code CLI is installed and callable."""
    try:
        result = subprocess.run(
            ["claude", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


# ---------------------------------------------------------------------------
# Internal UI helpers
# ---------------------------------------------------------------------------


def _print(msg: str = "", end: str = "\n") -> None:
    print(msg, end=end, flush=True)


def _die(msg: str, code: int = 1) -> None:
    print(f"\n❌  {msg}", file=sys.stderr)
    sys.exit(code)


def _prompt(prompt: str, default: str = "") -> str:
    """Prompt user for input with an optional default."""
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        _print()
        _die("Setup cancelled.")
    return val or default


def _prompt_choice(prompt: str, choices: list[str], default: str = "") -> str:
    """Prompt user to pick one of the given choices (case-insensitive)."""
    opts = "/".join(c.upper() if c.lower() == default.lower() else c for c in choices)
    while True:
        val = _prompt(f"{prompt} ({opts})", default=default).lower()
        if val in [c.lower() for c in choices]:
            return val
        _print(f"  Please enter one of: {', '.join(choices)}")


# ---------------------------------------------------------------------------
# cmd_setup — interactive setup wizard
# ---------------------------------------------------------------------------


async def _run_setup(env_path: Path) -> None:
    _print()
    _print("╔══════════════════════════════════════════════════════╗")
    _print("║          ccdb setup — interactive wizard             ║")
    _print("╚══════════════════════════════════════════════════════╝")
    _print()

    # --- Check for existing .env -------------------------------------------
    overwrite = False
    if env_path.exists():
        _print(f"  ⚠️  {env_path} already exists.")
        ans = _prompt_choice("  Overwrite it?", ["y", "n"], default="n")
        if ans == "n":
            _die("Setup cancelled. Existing .env was not modified.")
        overwrite = True

    # --- Check Claude CLI ---------------------------------------------------
    _print()
    _print("Step 1 — Claude Code CLI")
    if check_claude_cli():
        _print("  ✅  claude found")
    else:
        _print("  ⚠️  'claude' command not found.")
        _print("      Install Claude Code: https://docs.anthropic.com/en/docs/claude-code")
        _print("      (You can continue setup now and install Claude Code later.)")

    # --- Discord bot token -------------------------------------------------
    _print()
    _print("Step 2 — Discord Bot Token")
    _print("  Where to get it: discord.com/developers/applications → Bot → Reset Token")
    _print()

    token = ""
    bot_name = ""
    for attempt in range(3):
        token = _prompt("  Bot Token")
        if not token:
            _print("  Token cannot be empty.")
            continue
        _print("  Validating token… ", end="")
        sys.stdout.flush()
        bot_name = await validate_token(token)
        if bot_name:
            _print(f"✅  Logged in as {bot_name}")
            break
        _print("❌  Invalid token. Please check and try again.")
        if attempt == 2:
            _die("Too many failed attempts. Please verify your bot token.")
        token = ""

    # --- Channel ID — try API first, fallback to manual -------------------
    _print()
    _print("Step 3 — Discord Channel ID")
    channel_id = ""

    _print("  Fetching channels via Discord API… ", end="")
    sys.stdout.flush()
    channels = await fetch_channels(token)

    if channels:
        _print(f"✅  Found {len(channels)} text channel(s)\n")
        for i, (_cid, cname, gname) in enumerate(channels, 1):
            _print(f"  {i:2}. #{cname}  ({gname})")
        _print()

        while True:
            raw = _prompt(f"  Select channel [1-{len(channels)}] or paste ID directly")
            if raw.isdigit():
                idx = int(raw)
                if 1 <= idx <= len(channels):
                    channel_id = channels[idx - 1][0]
                    _print(f"  ✅  #{channels[idx - 1][1]} ({channel_id})")
                    break
                # maybe it's an 18-digit Discord ID
                if len(raw) >= 17:
                    channel_id = raw
                    _print(f"  ✅  Channel ID: {channel_id}")
                    break
                _print(f"  Enter a number between 1 and {len(channels)}, or paste the ID.")
            elif len(raw) >= 17:
                channel_id = raw
                _print(f"  ✅  Channel ID: {channel_id}")
                break
            else:
                _print("  That doesn't look like a valid channel ID. Try again.")
    else:
        _print("(bot not in any server yet — switching to manual entry)\n")
        _print("  Tip: In Discord → Settings → Advanced → enable Developer Mode,")
        _print("       then right-click the channel → Copy Channel ID.")
        while True:
            raw = _prompt("  Channel ID")
            if len(raw) >= 17 and raw.isdigit():
                channel_id = raw
                break
            _print("  Channel IDs are 17-19 digit numbers. Please try again.")

    # --- Owner user ID (optional) -----------------------------------------
    _print()
    _print("Step 4 — Your Discord User ID  (optional — used for @-mentions)")
    _print("  Tip: Right-click your username → Copy User ID  (Developer Mode required)")
    owner_id = _prompt("  Your User ID", default="")

    # --- Working directory -------------------------------------------------
    _print()
    _print("Step 5 — Working Directory")
    _print("  The directory where Claude Code will run (your project root).")
    default_wd = os.getcwd()
    working_dir = _prompt("  Working directory", default=default_wd)

    # --- Model selection --------------------------------------------------
    _print()
    _print("Step 6 — Claude Model")
    model = _prompt_choice(
        "  Model",
        ["sonnet", "opus", "haiku"],
        default="sonnet",
    )

    # --- Write .env -------------------------------------------------------
    _print()
    write_env(
        path=env_path,
        token=token,
        channel_id=channel_id,
        owner_id=owner_id,
        working_dir=working_dir,
        model=model,
        overwrite=overwrite,
    )
    _print(f"  ✅  Written: {env_path}")

    # --- Summary ----------------------------------------------------------
    _print()
    _print("╔══════════════════════════════════════════════════════╗")
    _print("║  Setup complete! Start the bot with:                 ║")
    _print("║                                                      ║")
    _print("║    ccdb start                                        ║")
    _print("║                                                      ║")
    _print("║  Then send a message in your Discord channel.        ║")
    _print("╚══════════════════════════════════════════════════════╝")
    _print()

    # --- Offer to start immediately ---------------------------------------
    if sys.stdin.isatty():
        ans = _prompt_choice("  Start the bot now?", ["y", "n"], default="y")
        if ans == "y":
            await _run_start(env_path)


def cmd_setup(env_path: Path = Path(".env")) -> None:
    """Entry point for `ccdb setup`."""
    asyncio.run(_run_setup(env_path))


# ---------------------------------------------------------------------------
# cmd_start — launch the bot
# ---------------------------------------------------------------------------


async def _run_start(env_path: Path) -> None:
    if not env_path.exists():
        print(f"❌  No .env file found at {env_path}.", file=sys.stderr)
        print("    Run 'ccdb setup' first to create it.", file=sys.stderr)
        sys.exit(1)

    # Import and run the existing main() from claude_discord.main
    from claude_discord.main import main as bot_main

    await bot_main()


def cmd_start(env_path: Path = Path(".env")) -> None:
    """Entry point for `ccdb start`."""
    if not env_path.exists():
        print(f"❌  No .env file found at {env_path}.", file=sys.stderr)
        print("    Run 'ccdb setup' first.", file=sys.stderr)
        sys.exit(1)
    asyncio.run(_run_start(env_path))


# ---------------------------------------------------------------------------
# main() — argument parsing
# ---------------------------------------------------------------------------


def main() -> None:
    """Top-level entry point registered in pyproject.toml [project.scripts]."""
    parser = argparse.ArgumentParser(
        prog="ccdb",
        description="claude-code-discord-bridge CLI",
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")

    # setup
    setup_parser = sub.add_parser("setup", help="Interactive setup wizard — creates .env")
    setup_parser.add_argument(
        "--env",
        default=".env",
        metavar="PATH",
        help="Path to write the .env file (default: .env)",
    )

    # start
    start_parser = sub.add_parser("start", help="Start the bot (reads .env)")
    start_parser.add_argument(
        "--env",
        default=".env",
        metavar="PATH",
        help="Path to the .env file (default: .env)",
    )

    args = parser.parse_args()

    if args.command == "setup":
        cmd_setup(Path(args.env))
    elif args.command == "start":
        cmd_start(Path(args.env))
    else:
        parser.print_help()
        sys.exit(0)
