#!/usr/bin/env bash
# =============================================================================
# install-systemd.sh — run c-lord as a systemd --user service (survives reboot)
# =============================================================================
# Installs deploy/c-lord.service **verbatim** as ~/.config/systemd/user/c-lord.service
# and writes the host-specific values (THIS clone's path, your `uv`, your PATH) to a
# drop-in, c-lord.service.d/10-install.conf. Then enables it and turns on linger so
# it starts on boot without a login.
#
# Why verbatim + drop-in: the unit that runs production must be the one in the repo.
# A hand-edited unit (or one that execs an untracked launcher script) drifts from
# what the repo says, and nobody reading the repo can tell how prod really starts.
# `bash scripts/staging.sh status` warns when the installed unit differs from
# deploy/c-lord.service.
#
# Idempotent: safe to re-run (regenerates the unit + re-enables). No root needed
# for the service itself; `loginctl enable-linger` may prompt for sudo on some
# distros. Requires a user systemd instance (standard on desktop/server Ubuntu).
#
# After a code update, restart with:  systemctl --user restart c-lord.service
# =============================================================================
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UNIT_NAME="c-lord.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_PATH="$UNIT_DIR/$UNIT_NAME"

UV="$(command -v uv || true)"
if [ -z "$UV" ]; then
  echo "ERROR: 'uv' not found on PATH. Install it first: https://docs.astral.sh/uv/" >&2
  exit 1
fi
UV_DIR="$(dirname "$UV")"

# Build the service PATH from the installing shell's $PATH so the service finds
# claude / uv / tmux / git exactly like your interactive shell does (a systemd
# --user service otherwise gets a minimal PATH and can't spawn the claude CLI).
# Sanitize: keep only absolute, existing dirs, de-duplicated — drops relative
# entries (./node_modules/.bin) and stale/foreign paths that don't exist here.
SERVICE_PATH=""
add_dir() {
  # `return 0`, not a bare `return`: under `set -e` a non-zero return here would
  # silently abort the whole install on the first missing PATH entry.
  case "$1" in /*) ;; *) return 0 ;; esac          # absolute only
  [ -d "$1" ] || return 0                           # existing only
  case ":$SERVICE_PATH:" in *":$1:"*) return 0 ;; esac  # de-dup
  SERVICE_PATH="${SERVICE_PATH:+$SERVICE_PATH:}$1"
}
add_dir "$UV_DIR"
add_dir "$HOME/.local/bin"
IFS=: read -ra _path_parts <<<"$PATH"
for _d in "${_path_parts[@]}"; do add_dir "$_d"; done
for _d in /usr/local/bin /usr/bin /bin; do add_dir "$_d"; done

if [ ! -f "$REPO_DIR/.env" ]; then
  echo "WARNING: $REPO_DIR/.env not found — run 'uv run c-lord setup' first," >&2
  echo "         otherwise the service will start but fail to log in to Discord." >&2
fi

DROP_IN_DIR="$UNIT_PATH.d"
DROP_IN="$DROP_IN_DIR/10-install.conf"
mkdir -p "$UNIT_DIR" "$DROP_IN_DIR"
install -m 0644 "$REPO_DIR/deploy/c-lord.service" "$UNIT_PATH"
cat > "$DROP_IN" <<EOF
# Generated by scripts/install-systemd.sh — host-specific values for c-lord.service.
# The unit itself is deploy/c-lord.service verbatim; re-run the script to regenerate.
[Service]
WorkingDirectory=$REPO_DIR
# The empty ExecStart= clears the unit's one; without it systemd would add a second.
ExecStart=
ExecStart=$UV run python -m c_lord.main
Environment=PATH=$SERVICE_PATH
EOF
echo "wrote $UNIT_PATH (= deploy/c-lord.service)"
echo "wrote $DROP_IN"
echo "  WorkingDirectory=$REPO_DIR"
echo "  ExecStart=$UV run python -m c_lord.main"

systemctl --user daemon-reload
# A unit systemd gave up on (`Start request repeated too quickly`) refuses to start
# until its failure counter is reset.
systemctl --user reset-failed "$UNIT_NAME" 2>/dev/null || true
systemctl --user enable --now "$UNIT_NAME"

# Linger: keep the user manager (and thus this service) running after logout and
# start it on boot without a login session.
if loginctl show-user "$USER" 2>/dev/null | grep -q '^Linger=yes'; then
  echo "linger already enabled for $USER"
else
  echo "enabling linger for $USER (start on boot without login)…"
  loginctl enable-linger "$USER" 2>/dev/null || sudo loginctl enable-linger "$USER"
fi

echo
systemctl --user status "$UNIT_NAME" --no-pager || true
echo
echo "Done. Manage the service with:"
echo "  systemctl --user restart c-lord.service    # after a git pull (and to apply a re-installed unit)"
echo "  systemctl --user stop    c-lord.service"
echo "  systemctl --user status  c-lord.service"
echo "  journalctl --user -u c-lord.service -f     # live logs"
